// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7P-_y8qB8aLSn6c4gP3Vw5QwiuEr7yFE',
    appId: '1:525406223009:web:2eb390494b6f1419540ee0',
    messagingSenderId: '525406223009',
    projectId: 'auth-e13d3',
    authDomain: 'auth-e13d3.firebaseapp.com',
    storageBucket: 'auth-e13d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeYaR44gPaR1HCdDqOFl5SzmR-kTDFu00',
    appId: '1:525406223009:android:c4e3a8a27aac6ac3540ee0',
    messagingSenderId: '525406223009',
    projectId: 'auth-e13d3',
    storageBucket: 'auth-e13d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACDM2c-jeCvNwwD-ogUXxc38wIHxyEEgE',
    appId: '1:525406223009:ios:f9d8dea7fe78a9a8540ee0',
    messagingSenderId: '525406223009',
    projectId: 'auth-e13d3',
    storageBucket: 'auth-e13d3.appspot.com',
    iosBundleId: 'com.example.authWithGoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACDM2c-jeCvNwwD-ogUXxc38wIHxyEEgE',
    appId: '1:525406223009:ios:f9d8dea7fe78a9a8540ee0',
    messagingSenderId: '525406223009',
    projectId: 'auth-e13d3',
    storageBucket: 'auth-e13d3.appspot.com',
    iosBundleId: 'com.example.authWithGoogle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7P-_y8qB8aLSn6c4gP3Vw5QwiuEr7yFE',
    appId: '1:525406223009:web:7f46b52d05f8400a540ee0',
    messagingSenderId: '525406223009',
    projectId: 'auth-e13d3',
    authDomain: 'auth-e13d3.firebaseapp.com',
    storageBucket: 'auth-e13d3.appspot.com',
  );
}
